/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.app.Fecha

fun main() {
   var fecha: Fecha
   fecha=Fecha()

   fecha.inicializar(2026,5,29)

   println(fecha.toString())
}
